name: build & deploy service

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # test: echo ${{ steps.date.outputs.date }}
      - name: create version
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build ui
        run: mvn -B --no-transfer-progress clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: ${{ steps.date.outputs.date }}, latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
